name: Test
on:
    push:
        branches-ignore:
            - master
    pull_request:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-16.04
        strategy:
            matrix:
                node: ["10"]
        name: Node ${{ matrix.node }}
        steps:
            - name: GIT - checkout
              uses: actions/checkout@v1
              with:
                  ref: master

            - name: GIT - prepare
              run: |
                  git checkout "${GITHUB_REF:11}"
                  git remote set-url origin https://lokesh-coder:${{ secrets.GITHUB_TOKEN }}@github.com/lokesh-coder/lesyjs.git
                  git config --global user.email "mexican.dirtyfellow@gmail.com"
                  git config --global user.name "lokesh-coder"

            - name: NODE - setup
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: NPM - install lerna
              run: npm install --global lerna

            - name: LERNA - bootstrap
              run: npm run bootstrap

            - name: NPM - lint
              run: npm run lint

            - name: NPM - test
              run: npm test
